const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let hw=null, debug=false, zoom=1, selectedDisk=null, guestGpu=null;
const titles={overview:'Ready check',hardware:'Hardware scan',storage:'Choose a disk',passthrough:'Passthrough plan',install:'Install'};
function addLog(msg,raw=false){const el=$('#log');const span=document.createElement('span');span.className=raw?'log-debug':'log-general';span.textContent=`${new Date().toLocaleTimeString()}  ${msg}\n`;el.appendChild(span);el.scrollTop=el.scrollHeight}
function gotoPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=titles[id]||'Desire VFIO'}
$$('.nav').forEach(b=>b.onclick=()=>gotoPage(b.dataset.page));$$('[data-goto]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.goto));
$('#debugToggle').onchange=e=>{debug=e.target.checked;document.body.classList.toggle('debug-on',debug);addLog(`Debug mode ${debug?'enabled':'disabled'}`)};
function applyZoom(){document.documentElement.style.setProperty('--scale',zoom.toFixed(2));$('#zoomValue').textContent=Math.round(zoom*100)+'%'}
$('#zoomIn').onclick=()=>{zoom=Math.min(1.35,zoom+.1);applyZoom()};$('#zoomOut').onclick=()=>{zoom=Math.max(.8,zoom-.1);applyZoom()};
let cx=0,cy=0;window.addEventListener('mousemove',e=>{cx=e.clientX;cy=e.clientY;$('#cursorDot').style.left=cx+'px';$('#cursorDot').style.top=cy+'px';requestAnimationFrame(()=>{$('#cursorGlow').style.left=cx+'px';$('#cursorGlow').style.top=cy+'px'})});
function badge(text,type='good'){return `<span class="badge ${type}">${text}</span>`}
function safe(v){return String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(data){hw=data; const checks=data.checks||[]; const bad=checks.filter(x=>x.level==='bad').length,warn=checks.filter(x=>x.level==='warn').length;
 $('#overallDot').className='dot '+(bad?'bad':warn?'warn':'good'); $('#overallText').textContent=bad?`${bad} blocking issue${bad>1?'s':''} found`:warn?`Ready with ${warn} recommendation${warn>1?'s':''}`:'Hardware looks ready';
 const summaries=[['Virtualization',data.cpu?.virt?'Available':'Not detected',data.cpu?.virt?'CPU VMX/SVM detected':'Enable CPU virtualization in firmware'],['IOMMU',data.iommu?.supported?'Supported':'Not detected',data.iommu?.groups?`${data.iommu.groups} active groups`:'Will be tested before VFIO is enabled'],['Graphics',`${(data.gpus||[]).length} GPU${(data.gpus||[]).length===1?'':'s'} detected`,data.gpus?.map(x=>x.short).join(' + ')||'No display adapter found']];
 $('#summaryCards').innerHTML=summaries.map(s=>`<div class="mini-card"><div class="label">${safe(s[0])}</div><div class="value">${safe(s[1])}</div><div class="note">${safe(s[2])}</div></div>`).join('');
 $('#recommendations').innerHTML=checks.map(c=>`<div class="check-row"><div><b>${safe(c.title)}</b><div class="gpu-meta">${safe(c.detail)}</div></div>${badge(c.level==='good'?'PASS':c.level==='warn'?'CHECK':'BLOCK',c.level)}</div>`).join('')||'<p>No recommendations yet.</p>';
 const c=data.cpu||{},b=data.bios||{}; $('#cpuInfo').innerHTML=[['CPU',c.model],['Virtualization flag',c.virt_flag||'none'],['UEFI',data.uefi?'Yes':'No'],['Board',b.board],['BIOS',b.version],['BIOS date',b.date],['Secure Boot',data.secure_boot]].map(([k,v])=>`<div class="k">${safe(k)}</div><div>${safe(v||'Unknown')}</div>`).join('');
 $('#gpuInfo').innerHTML=(data.gpus||[]).map((g,i)=>`<div class="gpu-row"><div><b>${safe(g.short)}</b><div class="gpu-meta">${safe(g.address)} · ${safe(g.id)} · ${safe(g.driver||'unbound')}</div></div>${badge(i===0?'Detected':'Candidate',i===0?'good':'warn')}</div>`).join('')||'<p class="muted">No GPU information returned.</p>';
 $('#iommuInfo').innerHTML=`<div class="check-row"><div><b>${data.iommu?.supported?'Firmware exposes IOMMU support':'IOMMU support not confirmed'}</b><div class="gpu-meta">DMAR: ${data.iommu?.dmar?'yes':'no'} · IVRS: ${data.iommu?.ivrs?'yes':'no'} · active groups: ${data.iommu?.groups||0}</div></div>${badge(data.iommu?.supported?'Detected':'Check BIOS',data.iommu?.supported?'good':'warn')}</div>`;
 $('#diskList').innerHTML=(data.disks||[]).map(d=>`<div class="disk-row" data-disk="${safe(d.path)}"><div><b>${safe(d.model||d.path)}</b><div class="disk-meta">${safe(d.path)} · ${safe(d.size_human)} · ${safe(d.tran||'unknown bus')} ${d.windows?'· Windows partitions detected':''}</div></div>${badge(d.removable?'Removable':d.windows?'Windows present':'Disk',d.removable?'warn':d.windows?'warn':'good')}</div>`).join('');
 $$('.disk-row').forEach(r=>r.onclick=()=>selectDisk(r.dataset.disk));
 const dg=(data.gpus||[]).find((g,i)=>i>0 && /NVIDIA|AMD|Radeon|GeForce/i.test(g.name||''))||data.gpus?.[1]; guestGpu=dg||null; $('#passthroughPlan').innerHTML=dg?`<div class="check-row"><div><b>Guest GPU candidate: ${safe(dg.short)}</b><div class="gpu-meta">${safe(dg.address)} · ${safe(dg.id)}</div></div>${badge('Test boot first','warn')}</div><p class="muted">Desire will generate a separate rollback-safe VFIO boot entry after installation. It will not automatically make it the default.</p>`:'<p class="muted">A dedicated guest GPU was not confidently identified.</p>';
 $('#installWarnings').innerHTML=bad?`<p style="color:var(--bad)">Resolve blocking hardware checks before installing.</p>`:warn?`<p style="color:var(--warn)">Review the recommendations above before installing.</p>`:`<p style="color:var(--good)">Pre-flight checks passed.</p>`;
 (data.raw||[]).forEach(x=>addLog(x,true)); addLog('Hardware scan complete.'); }
function selectDisk(path){selectedDisk=path;$$('.disk-row').forEach(x=>x.classList.toggle('selected',x.dataset.disk===path));const d=hw.disks.find(x=>x.path===path);let msg=`Selected ${d.model||d.path} (${d.size_human}). `;if(d.removable)msg+='This looks removable; verify it is not the installer USB.';else if(d.windows)msg+='Windows partitions were detected. Fedora installer will require explicit confirmation before deleting anything.';else msg+='No Windows partition signature was detected.';$('#diskGuard').textContent=msg;addLog(msg)}
const demoData={cpu:{model:'Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz',virt:true,virt_flag:'vmx'},uefi:true,iommu:{supported:true,dmar:true,ivrs:false,groups:14},bios:{board:'ASUSTeK COMPUTER INC. PRIME Z490-P',version:'Demo',date:'Demo'},secure_boot:'SecureBoot disabled',gpus:[{address:'0000:00:02.0',name:'Intel Corporation UHD Graphics 630',short:'UHD Graphics 630',id:'8086:9bc5',driver:'i915'},{address:'0000:01:00.0',name:'NVIDIA Corporation GeForce RTX 2080 SUPER',short:'GeForce RTX 2080 SUPER',id:'10de:1e81',driver:'unbound'}],disks:[{path:'/dev/sda',model:'Second SSD',size_human:'931.5 GiB',tran:'sata',removable:false,windows:false},{path:'/dev/nvme0n1',model:'Windows NVMe',size_human:'931.5 GiB',tran:'nvme',removable:false,windows:true}],checks:[{title:'CPU virtualization',detail:'VMX detected',level:'good'},{title:'UEFI boot',detail:'System is booted in UEFI mode',level:'good'},{title:'IOMMU capability',detail:'DMAR firmware support detected',level:'good'},{title:'Dual-GPU layout',detail:'2 display adapters detected; ideal for host + guest GPU',level:'good'},{title:'BIOS update',detail:'No update is forced; vendor/LVFS availability is checked when online.',level:'warn'},{title:'Existing Windows data',detail:'Windows partitions detected on /dev/nvme0n1. Verify the target before partition changes.',level:'warn'}],raw:['$ lspci -Dnnk','00:02.0 Intel UHD Graphics 630 -> i915','01:00.0 RTX 2080 SUPER -> unbound','$ find /sys/kernel/iommu_groups -type l','14 groups detected']};
async function scan(){addLog('Starting hardware pre-flight…');$('#overallText').textContent='Scanning hardware…';$('#overallDot').className='dot pending';if(location.protocol==='file:'||new URLSearchParams(location.search).has('demo')){render(demoData);addLog('Preview mode: showing sample hardware.');return}try{const r=await fetch('/api/scan');const d=await r.json();render(d)}catch(e){addLog('Scan failed: '+e,true);$('#overallText').textContent='Scan failed';$('#overallDot').className='dot bad'}}
$('#rescanBtn').onclick=scan;$('#clearLog').onclick=()=>$('#log').textContent='';
$('#installBtn').onclick=async()=>{if(!hw)return;if(!selectedDisk){gotoPage('storage');addLog('Choose an installation disk before opening the installer.');return}if((hw.checks||[]).some(x=>x.level==='bad')){addLog('Installation blocked by pre-flight checks.');return}if(!confirm(`Open Fedora installer?\n\nSelected disk for your attention: ${selectedDisk}\n\nNo disk is erased by this button; partition changes happen in Fedora's installer.`))return;addLog('Launching Fedora installer…');try{const r=await fetch('/api/launch-installer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({disk:selectedDisk})});const d=await r.json();if(!d.ok)addLog('Installer launch failed: '+d.error,true)}catch(e){addLog('Installer launch failed: '+e,true)}};
scan();

$('#makeTestBtn').onclick=async()=>{if(!guestGpu){addLog('No guest GPU candidate available.');return}if(!confirm(`Create a rollback-safe VFIO test boot entry for ${guestGpu.short}?\n\nThis does not change the default boot entry.`))return;addLog(`Requesting VFIO test entry for ${guestGpu.address}…`);try{const r=await fetch('/api/make-vfio-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pci:guestGpu.address})});const d=await r.json();if(d.ok)addLog(d.message||'VFIO test entry created.');else addLog('VFIO test entry failed: '+d.error,true)}catch(e){addLog('VFIO test entry failed: '+e,true)}};
$('#doctorBtn').onclick=async()=>{addLog('Running Desire VFIO Doctor…');try{const r=await fetch('/api/doctor',{method:'POST'});const d=await r.json();if(d.output){addLog(d.output,true);gotoPage('passthrough')}else addLog(d.error||'Doctor failed',true)}catch(e){addLog('Doctor failed: '+e,true)}};
